// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	ID        pgtype.UUID        `json:"id"`
	Text      string             `json:"text"`
	IsDone    bool               `json:"is_done"`
	DoneAt    pgtype.Timestamptz `json:"done_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Priority  int32              `json:"priority"`
	IsDeleted bool               `json:"is_deleted"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
