// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeTodo = `-- name: CompleteTodo :one
UPDATE todo
SET
    is_done = TRUE,
    done_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND is_deleted = FALSE
RETURNING id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
`

func (q *Queries) CompleteTodo(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, completeTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.IsDone,
		&i.DoneAt,
		&i.UserID,
		&i.Priority,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countTodosByUserID = `-- name: CountTodosByUserID :one
SELECT COUNT(*)
FROM todo
WHERE user_id = $1
  AND is_deleted = FALSE
`

func (q *Queries) CountTodosByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTodosByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todo (
    text,
    user_id,
    priority
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
`

type CreateTodoParams struct {
	Text     string      `json:"text"`
	UserID   pgtype.UUID `json:"user_id"`
	Priority int32       `json:"priority"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Text, arg.UserID, arg.Priority)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.IsDone,
		&i.DoneAt,
		&i.UserID,
		&i.Priority,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
FROM todo
WHERE id = $1
  AND is_deleted = FALSE
`

func (q *Queries) GetTodoByID(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.IsDone,
		&i.DoneAt,
		&i.UserID,
		&i.Priority,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompletedTodosByUserID = `-- name: ListCompletedTodosByUserID :many
SELECT id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
FROM todo
WHERE user_id = $1
  AND is_done = TRUE
  AND is_deleted = FALSE
ORDER BY done_at DESC
`

func (q *Queries) ListCompletedTodosByUserID(ctx context.Context, userID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listCompletedTodosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.IsDone,
			&i.DoneAt,
			&i.UserID,
			&i.Priority,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTodosByUserID = `-- name: ListPendingTodosByUserID :many
SELECT id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
FROM todo
WHERE user_id = $1
  AND is_done = FALSE
  AND is_deleted = FALSE
ORDER BY priority ASC, created_at DESC
`

func (q *Queries) ListPendingTodosByUserID(ctx context.Context, userID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listPendingTodosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.IsDone,
			&i.DoneAt,
			&i.UserID,
			&i.Priority,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByUserID = `-- name: ListTodosByUserID :many
SELECT id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
FROM todo
WHERE user_id = $1
  AND is_deleted = FALSE
ORDER BY created_at DESC
`

func (q *Queries) ListTodosByUserID(ctx context.Context, userID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.IsDone,
			&i.DoneAt,
			&i.UserID,
			&i.Priority,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTodo = `-- name: RestoreTodo :one
UPDATE todo
SET
    is_deleted = FALSE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
`

func (q *Queries) RestoreTodo(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, restoreTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.IsDone,
		&i.DoneAt,
		&i.UserID,
		&i.Priority,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todo
SET
    is_deleted = TRUE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTodo, id)
	return err
}

const uncompleteTodo = `-- name: UncompleteTodo :one
UPDATE todo
SET
    is_done = FALSE,
    done_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND is_deleted = FALSE
RETURNING id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
`

func (q *Queries) UncompleteTodo(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, uncompleteTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.IsDone,
		&i.DoneAt,
		&i.UserID,
		&i.Priority,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todo
SET
    text = $2,
    priority = $3,
    updated_at = NOW()
WHERE id = $1
  AND user_id = $4
  AND is_deleted = FALSE
RETURNING id, text, is_done, done_at, user_id, priority, is_deleted, created_at, updated_at
`

type UpdateTodoParams struct {
	ID       pgtype.UUID `json:"id"`
	Text     string      `json:"text"`
	Priority int32       `json:"priority"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.Text,
		arg.Priority,
		arg.UserID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.IsDone,
		&i.DoneAt,
		&i.UserID,
		&i.Priority,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
